#!/bin/bash

function help {
	echo "getip 1.1"
	echo "	Usage: getip [action] [option]"
	echo " "
	echo "  getip gives the current private or public IP which is using your host"
	echo "  action could be:"
	echo "     public   > public IP assigned by your ISP to your modem for internet connection"
	echo "     private  > private IP in your local network"
	echo "     help     > prints this message and exit"
	echo " "
	echo " Version 1.1 (12-sep-2016): - Added help message"
	echo "                            - Added default option showing both private, public IP's"
	echo " "
	echo "  Carlos Molina 2016"
}

if [[ $# = 0 ]]; then
	echo "Public IP"
	wget http://ipinfo.io/ip -qO -
	echo "Private IP"
	ip -4 -o addr show  | perl -lane 'print $F[3]'
	exit
fi

if [[ $1 = "private" ]]; then
	# Get local network IP
	ip -4 -o addr show  | perl -lane 'print $F[3]'
elif [[ $1 = "public" ]]; then
	 #Get publib IP
	if [[ $2 = "full" ]]; then
		wget http://ipinfo.io/ -qO -
		echo -e "\n"
	else
		wget http://ipinfo.io/ip -qO -
	fi
elif [[ $1 = "help" ]]; then
	help
	exit
fi
