#!/bin/bash
CFGDIR="$HOME/.config/public_ip"
FILE_HIST="$CFGDIR/public_ip_history"

if [[ $# = 0 ]]; then
	if [[ ! -f $FILE_HIST ]]; then
			# Si no existe
			mkdir -p $CFGDIR
		fi
		ip="`getip public`"
		text="`date +"%Y%m%d %H%M"` $ip"
		echo $text >> $FILE_HIST
		echo "  $ip guardada en $FILE_HIST"
	elif [[ $1 = "--list" || $1 = "-l" ]]; then
		# Show saved IP's
		cat $FILE_HIST
	else
		echo -e "$1: argumento invalido. \n  Use -l --list para listar todas las IPs publicas guardadas.\n  No use ningun argumento para guardar IP publica actual"
		exit 1
fi
